#!/usr/bin/env node
// ============================================================
// GET OBFUSCATED URLS - Helper Script
// ============================================================
// This script displays the obfuscated tracking URLs based on
// your current configuration (environment variables or auto-generated)

import { CONFIG, initConfig } from '../src/config/index.js';

// Parse command line arguments
const args = process.argv.slice(2);
const domain = args[0] || 'https://yourstore.com';

console.log('\n╔════════════════════════════════════════════════════════════╗');
console.log('║  TRACKLAY - OBFUSCATED TRACKING URLS                       ║');
console.log('║  VERSION 3.0.0 - LEGACY ROUTES REMOVED                     ║');
console.log('╚════════════════════════════════════════════════════════════╝\n');

console.log('⚠️  BREAKING CHANGE (v3.0.0)\n');
console.log('   All legacy detectable routes have been REMOVED:');
console.log('   ❌ /cdn/fbevents.js, /cdn/gtm.js, /cdn/gtag.js');
console.log('   ❌ /tr, /g/collect, /j/collect');
console.log('   ❌ /assets/*, /static/* variants\n');
console.log('   ✅ Only obfuscated UUID-based routes remain');
console.log('   📚 Migration guide: docs/MIGRATION-V3.md\n');

// Initialize config (reads from environment variables if set)
initConfig(process.env);

console.log(`📍 Domain: ${domain}\n`);

// Facebook Pixel URLs
console.log('🔵 FACEBOOK PIXEL (Meta Pixel)\n');
console.log('   Obfuscated Path (script + endpoint share same path):');
console.log(`   ${domain}/cdn/f/${CONFIG.ENDPOINTS_FACEBOOK}\n`);
console.log('   ℹ️  Same path for both script (GET) and endpoint (POST)\n');

// Google Analytics URLs
console.log('🔴 GOOGLE ANALYTICS / TAG MANAGER\n');

if (CONFIG.GTM_SERVER_URL) {
  console.log(`   GTM Server URL: ${CONFIG.GTM_SERVER_URL}\n`);

  console.log('   Obfuscated Path (script + endpoint share same path):');
  console.log(`   ${domain}/cdn/g/${CONFIG.ENDPOINTS_GOOGLE}\n`);

  console.log('   Usage Examples:');
  console.log(`   • GTM Script:  ${domain}/cdn/g/${CONFIG.ENDPOINTS_GOOGLE}?id=GTM-XXXXX`);
  console.log(`   • GA4 Script:  ${domain}/cdn/g/${CONFIG.ENDPOINTS_GOOGLE}?id=G-XXXXX`);
  console.log(`   • With Alias:  ${domain}/cdn/g/${CONFIG.ENDPOINTS_GOOGLE}?c=abc123\n`);
  console.log('   ℹ️  Same path for both script (GET) and endpoint (GET with v=2/tid=/_p=)\n');
} else {
  console.log('   ⚠️  GTM_SERVER_URL not configured');
  console.log('   Set GTM_SERVER_URL to enable Google Analytics endpoints\n');
}

// Configuration info
console.log('⚙️  CONFIGURATION\n');
console.log(`   Facebook Endpoint ID: ${CONFIG.ENDPOINTS_FACEBOOK}`);
console.log(`   Google Endpoint ID:   ${CONFIG.ENDPOINTS_GOOGLE}\n`);

if (CONFIG.ENDPOINTS_FACEBOOK.includes('-')) {
  const isAutoGenerated = CONFIG.ENDPOINTS_FACEBOOK.length === 36;
  if (isAutoGenerated) {
    console.log('   ℹ️  Using auto-generated UUIDs');
    console.log('   💡 TIP: Set custom UUIDs via environment variables for production\n');
  } else {
    console.log('   ✅ Using custom UUIDs\n');
  }
}

// Instructions
console.log('📖 NEXT STEPS\n');
console.log('   1. Copy the obfuscated URLs above');
console.log('   2. Update your Shopify theme with these URLs');
console.log('   3. Test that scripts load and tracking works');
console.log('   4. Monitor Events Manager (Facebook) and Real-Time (Google)\n');

console.log('   📚 Full migration guide: docs/OBFUSCATION.md');
console.log('   🔧 Environment setup:    .env.example\n');

console.log('💡 TIPS\n');
console.log('   • Use obfuscated URLs for maximum ad-blocker bypass');
console.log('   • Rotate UUIDs periodically for best results');
console.log('   • See docs/OBFUSCATION.md for advanced strategies');
console.log('   • IMPORTANT: Legacy routes no longer supported (v3.0.0+)\n');

// Generate new UUIDs suggestion
console.log('🔐 GENERATE NEW UUIDS\n');
console.log('   Run this command to generate new random UUIDs:\n');
console.log('   node -e "console.log(require(\'crypto\').randomUUID())"\n');
console.log('   Then set them in Cloudflare Dashboard or .env file\n');

console.log('═══════════════════════════════════════════════════════════════\n');
