#!/usr/bin/env node
// ============================================================
// GET OBFUSCATED URLS - Helper Script
// ============================================================
// This script displays the obfuscated tracking URLs based on
// your current configuration (environment variables or auto-generated)

import { CONFIG, initConfig } from '../src/config/index.js';

// Parse command line arguments
const args = process.argv.slice(2);
const domain = args[0] || 'https://yourstore.com';

console.log('\n╔════════════════════════════════════════════════════════════╗');
console.log('║  TRACKLAY - OBFUSCATED TRACKING URLS                       ║');
console.log('╚════════════════════════════════════════════════════════════╝\n');

// Initialize config (reads from environment variables if set)
initConfig(process.env);

console.log(`📍 Domain: ${domain}\n`);

// Facebook Pixel URLs
console.log('🔵 FACEBOOK PIXEL (Meta Pixel)\n');
console.log('   Obfuscated Endpoint (recommended):');
console.log(`   ${domain}/cdn/f/${CONFIG.FACEBOOK_ENDPOINT_ID}.js\n`);

console.log('   Obfuscated Script (recommended):');
console.log(`   ${domain}/cdn/f/${CONFIG.FACEBOOK_ENDPOINT_ID}-script.js\n`);

console.log('   Legacy Endpoint (detectable by ad-blockers):');
console.log(`   ${domain}/tr\n`);

console.log('   Legacy Script (detectable by ad-blockers):');
console.log(`   ${domain}/cdn/fbevents.js\n`);

// Google Analytics URLs
console.log('🔴 GOOGLE ANALYTICS / TAG MANAGER\n');

if (CONFIG.GTM_SERVER_URL) {
  console.log(`   GTM Server URL: ${CONFIG.GTM_SERVER_URL}\n`);

  console.log('   Obfuscated Endpoint (recommended):');
  console.log(`   ${domain}/cdn/g/${CONFIG.GOOGLE_ENDPOINT_ID}.js\n`);

  console.log('   Obfuscated GTM Script (recommended):');
  console.log(`   ${domain}/cdn/g/${CONFIG.GOOGLE_ENDPOINT_ID}-gtm.js?id=GTM-XXXXX\n`);

  console.log('   Obfuscated GTag Script (recommended):');
  console.log(`   ${domain}/cdn/g/${CONFIG.GOOGLE_ENDPOINT_ID}-tag.js?id=G-XXXXX\n`);

  console.log('   Legacy Endpoints (detectable by ad-blockers):');
  console.log(`   ${domain}/g/collect`);
  console.log(`   ${domain}/j/collect\n`);
} else {
  console.log('   ⚠️  GTM_SERVER_URL not configured');
  console.log('   Set GTM_SERVER_URL to enable Google Analytics endpoints\n');
}

console.log('   Legacy Scripts (detectable by ad-blockers):');
console.log(`   ${domain}/cdn/gtm.js?id=GTM-XXXXX`);
console.log(`   ${domain}/cdn/gtag.js?id=G-XXXXX\n`);

// Configuration info
console.log('⚙️  CONFIGURATION\n');
console.log(`   Facebook Endpoint ID: ${CONFIG.FACEBOOK_ENDPOINT_ID}`);
console.log(`   Google Endpoint ID:   ${CONFIG.GOOGLE_ENDPOINT_ID}\n`);

if (CONFIG.FACEBOOK_ENDPOINT_ID.includes('-')) {
  const isAutoGenerated = CONFIG.FACEBOOK_ENDPOINT_ID.length === 36;
  if (isAutoGenerated) {
    console.log('   ℹ️  Using auto-generated UUIDs');
    console.log('   💡 TIP: Set custom UUIDs via environment variables for production\n');
  } else {
    console.log('   ✅ Using custom UUIDs\n');
  }
}

// Instructions
console.log('📖 NEXT STEPS\n');
console.log('   1. Copy the obfuscated URLs above');
console.log('   2. Update your Shopify theme with these URLs');
console.log('   3. Test that scripts load and tracking works');
console.log('   4. Monitor Events Manager (Facebook) and Real-Time (Google)\n');

console.log('   📚 Full migration guide: docs/OBFUSCATION.md');
console.log('   🔧 Environment setup:    .env.example\n');

console.log('💡 TIPS\n');
console.log('   • Use obfuscated URLs for maximum ad-blocker bypass');
console.log('   • Legacy URLs kept for backward compatibility only');
console.log('   • Rotate UUIDs periodically for best results');
console.log('   • See docs/OBFUSCATION.md for advanced strategies\n');

// Generate new UUIDs suggestion
console.log('🔐 GENERATE NEW UUIDS\n');
console.log('   Run this command to generate new random UUIDs:\n');
console.log('   node -e "console.log(require(\'crypto\').randomUUID())"\n');
console.log('   Then set them in Cloudflare Dashboard or .env file\n');

console.log('═══════════════════════════════════════════════════════════════\n');
